### ISSUE TITLE
[1.18.1] [Fabric] Playdate crashes Bumblezone at startup

### ISSUE THREAD

**Issue by pewblaze** [TelepathicGrunt/Bumblezone-Fabric#50] opened 2022-02-15 13:13 UTC
I updated the Mod today & now ill get a crash after starting MC. 
You can see the Crash in the log file.
Not sure what happened.

[latest.log](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/8069347/latest.log)

I'm using Fabric. 
the_bumblezone_fabric-4.3.2+1.18.1
fabric-api-0.46.4+1.18
Fabric Modloader 0.13.2

**Comment by TelepathicGrunt** [comment] 2022-02-15 13:17
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1754::thebumblezone_bottleFluidInteract with priority 1000 cannot inject into net/minecraft/class_1754::method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271; merged by net.yoruniii.play date.mixin.GlassBottleItemMixin with priority 1000 [PREINJECT Applicator Phase -> the_bumblezone.mixins.json:items.GlassBottleUseMixin -> Prepare Injections ->  -> handler$ico000$thebumblezone_bottleFluidInteract(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;Lnet/minecraft/class_1799;Lnet/minecraft/class_239;Lnet/minecraft/class_2338;)V -> Prepare]

Looks like a conflict with this mod:
net.yoruniii.play date.mixin.GlassBottleItemMixin 

They are breaking my glass bottle mixin which is this
https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/latest-released/src/main/java/com/telepathicgrunt/the_bumblezone/mixin/items/GlassBottleUseMixin.java

I haven’t touched my glass bottle mixin in over two months so did you just put on Playdate or updated playdate? Either way, I’ll try reaching out to them soon about it

**Comment by TelepathicGrunt** [comment] 2022-02-15 13:29
I can’t find play date anywhere. Do you have a link to that mod?

**Comment by pewblaze** [comment] 2022-02-15 15:17
https://www.curseforge.com/minecraft/mc-mods/playdate

Its a new mod, i downloaded it today too. didnt think about that :)

**Closed as completed** 2022-08-12 23:15 UTC
Labels: mod conflict
