### ISSUE TITLE
(1.16.3) Unknown Mod Interaction Kills Water As A Concept

### ISSUE THREAD

**Issue by runningwithscissors1337** [TelepathicGrunt/Bumblezone-Fabric#17] opened 2020-10-28 02:05 UTC
I have spent the past few hours attempting to track down a bug in my personal modpack that causes water to act like air blocks (no swimming/color change, standard gravity, etc). I have finally tracked the bug back to this specific mod, my primary suspicion at the time of writing is some kind of interaction between BetterCaves, Optifabric, and Optifine, as every other mod that remained had very little if anything to do with water, I will attempt to update this with the issue mod and an error log.

**Comment by TelepathicGrunt** [comment] 2020-10-28 02:08
A log would be helpful a ton but if optifine is involved, then it is most likely impossible for me to fix the bug on my end as optifine closed source and wrecks everyone due to it's massive replacements of entire swaths of code

**Comment by runningwithscissors1337** [comment] 2020-10-28 02:16
good to know, I created several logs in my search for the cause of this bug so I will be able to post all of them later tonight, I will also be testing a completely clean installation running nothing but Optifabric, Optifine, Better Caves, and this and try to cut it down to whatever mod is the problem

**Comment by runningwithscissors1337** [comment] 2020-10-28 18:24
Optifine was a dead end but I went through a lot of the mods I was using and found that Limitless, a mod i was using until very recently, has an identical bug, I tested it and lo and behold, removing Limitless fixes the issue just as much as removing The Bumblezone, uncertain what causes it, but i have attached the past few logs of me attempting to isolate the issue, theoretically the bug will not appear on the most recent log, but will appear on the one before it, but just in case I added the two before as well.
[latest.log](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5454064/latest.log)
[2020-10-28-7.log.gz](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5454069/2020-10-28-7.log.gz)
[2020-10-28-6.log.gz](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5454071/2020-10-28-6.log.gz)
[2020-10-28-5.log.gz](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5454072/2020-10-28-5.log.gz)

**Comment by TelepathicGrunt** [comment] 2020-11-05 00:58
I just tested with Limitless and Bumblezone on and water seems to be fine for me. Not sure what is happening. Is this still a problem right now? Does it happen if you make a new world with all the mods on? If so, can you send me a zip file of all the mods so I can try and reproduce the issue?

**Comment by TelepathicGrunt** [comment] 2020-11-21 22:33
I guess I'll close this issue report then lol. let me know if this still happens with latest bumblezone and if so, please try to give me the mod folder with the mods so I can quickly test and reproduce the issue

**Comment by runningwithscissors1337** [comment] 2021-02-27 21:02
Sorry for never responding to this @TelepathicGrunt, had an unrelated situation around the time you responded and completely forgot this was happening, I've felt like shit since for ignoring you, I've attempted to reproduce it with current versions of both mods and nothing works, I think I saw something from limitless about the issue being with another mod either way, but it seems to me like the issue was more on my side, sorry again for not responding to you

**Comment by TelepathicGrunt** [comment] 2021-02-27 21:05
Ah that's ok lol. No hard feelings! Though I am interested about this issue so if you can give me your mod list, I can see if I can narrow down the mod that's nuking my water

**Comment by runningwithscissors1337** [comment] 2021-02-27 21:08
ok, I'll be trying to recreate it, issue being I believe the mod folder has long since been deleted, if my terrible memory is accurate there was a comment on limitless with the issue so I'll look and test there, will update soon

**Comment by runningwithscissors1337** [comment] 2021-02-27 21:41
my previous logs no longer open properly and all evidence bar this thread this issue ever existed seem scrubbed from the internet, no files from the original modpack still exist on my pc, including the history from chrome, can't find any old versions of the mod pages with the wayback machine, etc, so I am completely lost, sorry for reawakening this bug, seems it dropped dead before it could be fixed lol

**Closed** 2021-02-27 22:03 UTC
Labels: bug, mod conflict

**Comment by TelepathicGrunt** [comment] 2021-02-27 22:07
Rip. oh well. I'll keep an eye out on if anyone else faces the same issue. But thank you for trying to help out!

**Comment by runningwithscissors1337** [comment] 2021-02-27 22:08
np, sorry again for ignoring you lol, I wish you luck
