### ISSUE TITLE
Invalid Player Data Error

### ISSUE THREAD

**Issue by Bullseye55** [TelepathicGrunt/Bumblezone-Fabric#35] opened 2021-11-14 03:09 UTC
When added to my modpack(of which I've updated the mods from previous versions in which The Bumblezone worked with), upon connecting to a newly-generated singleplayer world, I am disconnected due to invalid player data with the accompanying screen. No crash log is generated.

I've attached the log that goes through pack load, world generation, and then the disconnect+shutdown. This pack works fine if The Bumblezone is not added. MCDoom also gives invalid player data if added.

[latest.log](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/7533113/latest.log)

**Comment by TelepathicGrunt** [comment] 2021-11-14 04:50
Just linking Mc doom issue report to here too. https://github.com/AzureDoom/MCDoom/issues/19

See my response in Mc doom for more info and troubleshooting we can do to try and narrow down the issue

**Comment by TelepathicGrunt** [comment] 2021-11-15 23:35
Closing issue report as the cause of the issue is that the modpack had too much data to sync to itself lol
https://github.com/AzureDoom/MCDoom/issues/19#issuecomment-969437392

Nothing to do with bumblezone thankfully! Just means some mods need to be removed or XLpackets to increase the packet size even more

**Closed as completed by TelepathicGrunt** 2021-11-15 23:35 UTC
