### ISSUE TITLE
Immense logspam after removal of the mod

### ISSUE THREAD

**Issue by Skeithh** [TelepathicGrunt/Bumblezone-Fabric#43] opened 2022-01-24 18:22 UTC
Hi, after removing the mod with the instructions provided by telepathicgrunt on the curseforge page, all in all things went fine at first. Dimensions didn't vanish etc etc, and all blocks were deleted fine. After a server restart post-deletion, suddenly everything went to hell. What I am getting problems with, is immense logspam in the form of this

![image](https://user-images.githubusercontent.com/74820899/150841110-0cc77325-49d1-4e2c-aa7a-62885ac1ed73.png)
It is quite literally endless.

I have *no* idea how to approach this 

Fabric: 0.12.12
Removed version of bumblezone: 4.2.1
MC version: 1.18.1

**Comment by Skeithh** [comment] 2022-01-24 18:26
Additional... logspam of concern
![image](https://user-images.githubusercontent.com/74820899/150842072-b6158040-b4e9-4935-8f4b-1cd30bb787aa.png)

**Comment by TelepathicGrunt** [comment] 2022-01-24 18:37
These are just logspam but will not negatively impact the game. Cardinal Components logspams if it detects a component that is no longer existing due to removing a mod. The structure logspam is from vanilla when removing any mod with structures. Both are normal and just something to live with when removing mods from a world. 

You probably could find a mod that lets you silence certain messages from the logs. I believe All of Fabric 4 has said mod so you could look into that modpack and use that mod to clean up your logs if it is important.

But yeah, this is kinda the expected behavior when removing any content mod from existing worlds.

**Comment by Skeithh** [comment] 2022-01-24 18:39
ugh, that's not great at all because I kind of actually need the logs to be readable and not 99% bumblezone. 
I haven't had this issue with removing other mods at all which is why this became so alarming.

**Comment by TelepathicGrunt** [comment] 2022-01-24 19:41
The other mods you removed probably don’t use cardinal components or aren’t structure mods. The funny thing is the structure logspam when removing structure mods is actually on purpose by Fabric API. When they fixed an old bug where removing structure mods breaks the game, they chose to not turn off the logspam as they thought it was important for players to see. It really isn’t lol.

the mod that AoF uses to filter out logspam was Shut Up Console which seems like it will run on 1.18 despite being marked as 1.16 https://www.curseforge.com/minecraft/mc-mods/shut-up-console

**Comment by TelepathicGrunt** [comment] 2022-02-02 12:25
Closing this as there isn’t anything I can do. It’s up to the Fabric API folks to change their mind about keeping the logspam for structure removals.

There is this for removing the structure references but it says it is having issues in 1.18.1. https://github.com/Nyveon/MCStructureCleaner

**Closed as completed by TelepathicGrunt** 2022-02-02 12:25 UTC
Labels: wontfix
